.TH std::exception::exception 3 "2020.03.24" "http://cppreference.com" "C++ Standard Libary"
.SH NAME
std::exception::exception \- std::exception::exception

.SH Synopsis

exception() throw();                                  \fI(until C++11)\fP
exception() noexcept;                         \fB(1)\fP     \fI(since C++11)\fP
exception( const exception& other ) throw();      \fB(2)\fP               \fI(until C++11)\fP
exception( const exception& other ) noexcept;                       \fI(since C++11)\fP

Constructs new exception object.
1) Default constructor. what() returns an implementation-defined string.
2) Copy constructor. Initializes the contents with those of other.
If *this and other both have dynamic type std::exception then std::strcmp(what(), other.what()) == 0.
\fI(since C++11)\fP

.SH Parameters


other - another exception to assign the contents of


.SH Notes

Because copying std::exception is not permitted to throw exceptions, when derived classes (such as std::runtime_error) have to manage a user-defined diagnostic message, it is typically implemented as a copy-on-write string.



